baseURL = "https://community.datawallet.com/"
languageCode = "en-us"
title = "FAQ"

publishDir = "docs"

googleAnalytics = ""


theme = "hyde"
[params]
  themeColor = "theme-base-0d"
  description = "Some stuff for Datawallet community"

